### ISSUE TITLE
Add "Transpile" option to es6-fiddle

### ISSUE THREAD

**Issue by netpoetica** [jmcriffey/es6-fiddle-web#5]
Improvement maybe, would be interesting when toying with ES6 in the browser to also see the transpiled version of the code

**Comment by kimgysen** [comment]
Might this be relevant again with the switch from Traceur to Babel? 
Regarding the space in the page; I see that there are already three buttons available: "run", "lint" and "save". Having a supplementary button added to show the transpiled code would hide the interface from people who are not interested with minimum disadvantage. Or perhaps a button in the header of the console itself to "switch" between the transpiled code and the output. 
Perhaps it's true that this could mainly be important for educational purpose, but nevertheless I 'could' propagate a significant increase of traffic to your website since many people are yet to learn the ES6 syntax and it becomes increasingly relevant. Also, the very first question that popped my mind when I arrived on the website was which transpiler was used to make the transpilation, might be useful for pure informative purpose. Just my two cents.
